# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Barkodo_Customer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Barkodo_Customer

  target 'Barkodo_Customer-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Barkodo_CustomerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Barkodo_Customer-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Barkodo_Customer-tvOS

  target 'Barkodo_Customer-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
